name: Build ImmortalWrt

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * 5'
  workflow_dispatch:

env:
  REPO_URL: https://github.com/zhoufuli/immortalwrt-rk356x
  REPO_BRANCH: main
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Maximize disk space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 2048
          root-reserve-mb: 2560
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
        
      - name: Install dependencies
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison gperf texinfo libncurses-dev python3 libncurses5-dev python3-dev python3-setuptools libssl-dev gettext zlib1g-dev file wget git curl unzip gettext pkg-config gawk diffutils xz-utils bc automake cmake device-tree-compiler ccache libtool autoconf autogen m4 python3-pip
          df -h
        
      - name: Clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          df -h
          
      - name: Install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Load custom configuration
        run: |
          cd openwrt
          cp ${{ github.workspace }}/configs/g68_mtk_wifi.config .config
          
      - name: Download packages
        run: |
          cd openwrt
          make defconfig
          make download -j8
          
      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc) world
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: openwrt/bin/targets/rockchip/armv8/*.img.gz
          retention-days: 7
